### ISSUE TITLE
pvinverter pvtotal

### ISSUE THREAD

**Issue by Aikawa24** [sfstar/hass-victron#13]
hi, ive a problem with the measurement of pvinverter pvtotal it shows 130KW but it should show 0,13KW

sensor.victron_pvinverter_power_total_20

the sensors 
sensor.victron_pvinverter_l1_power_20
sensor.victron_pvinverter_l2_power_20
sensor.victron_pvinverter_l3_power_20

shows correct in W

can you fix this please?

thank you for your work :-)

**Comment by sfstar** [comment]
Hello and thank you for opening this issue.
I've also got a pvinverter which i just added to the vrm environment and I'm seeing the same behaviour.
However, it seems that this is a victron GX issue for the specific register.

Since the register definition states:
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/6717280/209219542-2b0969c7-5e98-4d48-8a58-7505ecaec790.png">


Which in the home assistant core integration modbus yaml would translate into (with off course your own gx device ip instead off <ip>):
```
 - name: victron
   type: tcp
   host: <ip>
   port: 502
   retry_on_empty: true
   retries: 10
   close_comm_on_error: true
   sensors:
      - name: victron_pvinverter_L1_power
        unit_of_measurement: "W"
        address: 1029
        slave: 30
        device_class: power
        state_class: measurement
        data_type: uint16   
      - name: victron_pvinverter_power_total
        unit_of_measurement: "kW"
        address: 1052
        slave: 30
        device_class: power
        state_class: measurement
        data_type: int32
```

Which also returns the incorrect scaled value for the power_total register.
So either there is a error in the documentation of victron or there is a bug in the modbus tcp server code of the GX device.

I'm affraid I can't solve this issue without starting to assume behaviour of the GX device.
Although this could solve our problem, assuming the actual intended data format outside of the official spec could cause issues down the line.
For example if victron patches this bug (in a newer version) then the integration would be reporting incorrect values for that newer version.

Therefore, I'm not going to change (/allow any changes) that would force the integration to diverge from the victron modbus TCP spec.
If victron were to update the spec then I'm willing to patch the integration to match it.
For now the best thing to do is to make victron aware of this bug so that it might get resolved.
