### ISSUE TITLE
Crash resulting from unhandled exception (struct.error: unpack requires a buffer of 2 bytes)

### ISSUE THREAD

**Issue by lewis2e** [sfstar/hass-victron#335]
## The problem

I am experiencing frequent crashes of the integration caused by the unhandled exception shown below. When this happens, none of the sensors within the integration will update until HomeAssistant is restarted.

I have not observed any pattern for this occurring. It seems random ranging from nothing in a few days to more than once per day.

## Environment

- Home Assistant Core release with the issue: 2025.5.3
- Last working Home Assistant Core release (if known): N/A
- Integration version causing this issue: 0.5.0

## Problem-relevant `configuration dialog`

```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


template:
  - sensor:
      - name: Home Battery Charge Rate Abs
        unique_id: home_battery_charge_rate_abs
        unit_of_measurement: "W"
        state: >
          {% set value = states('sensor.victron_system_battery_power') | float(0) %}
          {{ value * -1 if value < 0 else value }}
          
  - sensor:
      - name: Grid Rate Abs
        unique_id: grid_rate_abs
        unit_of_measurement: "W"
        state: >
          {% set value = states('sensor.victron_system_grid_l1') | float(0) %}
          {{ value * -1 if value < 0 else value }}


```

## Traceback/Error logs

```Log details (ERROR)
This error originated from a custom integration.
Logger: custom_components.victron.coordinatorSource: helpers/update_coordinator.py:380integration: victron (documentation, issues)First occurred: 17:33:43 (735 occurrences)Last logged: 18:55:03
Unexpected error fetching victron data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/victron/[coordinator.py](http://coordinator.py/)", line 97, in _async_update_data
    self.parse_register_data(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        data, register_info_dict[name], unit
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ).items()
    ^
  File "/config/custom_components/victron/[coordinator.py](http://coordinator.py/)", line 127, in parse_register_data
    decoder.decode_16bit_uint(), value.scale, value.unit
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/pymodbus/[payload.py](http://payload.py/)", line 413, in decode_16bit_uint
    return unpack(fstring, handle)[0]
           ~~~~~~^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 2 bytes

```
