### ISSUE TITLE
regular "lost connection" after update to 0.0.9

### ISSUE THREAD

**Issue by pos-ei-don** [sfstar/hass-victron#64]
Some values, especially my Victron mppt 3 and 4 stop sending Data to HA after several hours running.
I did not see this using 0.8 of this plugin.
I just revertet to check if this is solved with downgrading.

To reproduce this error, i just have to wait several hours. I see it when an MPPT gets a straigt line 
in ots power-value. Then it stopped updating this, while other Values still gets updated.
The Victron Console and the VRM still gets updated values from the device!

**Comment by pos-ei-don** [comment]
This is stable in v0.0.8. Didn't have any disconnects the ast 3 days.

**Comment by pos-ei-don** [comment]
Lost connection again today.
What I don't understand is why the orange Device recived data again after ~1hour while the purple didn't.
The VRM shows that both devices keept sending Data and still produced power.

So i think that this addon does not detect connection-disconnects and does nor reconnect automatically?
 When I manually "reload" the this integration, the data gets in again!

![grafik](https://user-images.githubusercontent.com/1822533/226329316-8ad00ab6-54f3-4097-9889-c2e579dc4e4d.png)

**Comment by seidler2547** [comment]
I solved it for now with this automation:
```
alias: Reload victron integration
description: ""
trigger:
  - platform: time_pattern
    minutes: /1
condition:
  - condition: template
    value_template: >-
      {{ (((as_timestamp(now()) -
      as_timestamp(states.sensor.victron_battery_current_4.last_updated))  / 60)
      |  int) > 2 }}
action:
  - service: homeassistant.reload_config_entry
    data: {}
    target:
      entity_id: sensor.victron_battery_current_4
mode: single
```
(Replace _4 with the ID of your battery)
